---
bibliography: bib/references.bib
---

```{r setup}
library(easypackages)
packages <- c('nonlinSims','tidyverse')
libraries(packages)
```

```{r presentation_slides}


theta <- 3
alpha <- 3.32
beta <- 180
gamma <- 20
time <- 0:360

#curve scores
logistic_curve <- theta + (alpha - theta)/(1 + exp((beta-time)/gamma))

logistic_data <- data.frame('score' = logistic_curve, 
                            'day' = time)

#day scores
equal_spacing_5 <- data.frame('day' = compute_measurement_schedule(time_period = 360, num_measurements = 5, smallest_int_length = 30, measurement_spacing = 'equal')$measurement_days)
equal_spacing_7 <- data.frame('day' = compute_measurement_schedule(time_period = 360, num_measurements = 7, smallest_int_length = 30, measurement_spacing = 'equal')$measurement_days)
equal_spacing_9 <- data.frame('day' = compute_measurement_schedule(time_period = 360, num_measurements = 9, smallest_int_length = 30, measurement_spacing = 'equal')$measurement_days)
equal_spacing_11 <- data.frame('day' = compute_measurement_schedule(time_period = 360, num_measurements = 11, smallest_int_length = 30, measurement_spacing = 'equal')$measurement_days)


#provide curve score for each point 
equal_spacing_5$score <- logistic_data$score[logistic_data$day %in% equal_spacing_5$day]
equal_spacing_7$score <- logistic_data$score[logistic_data$day %in% equal_spacing_7$day]
equal_spacing_9$score <- logistic_data$score[logistic_data$day %in% equal_spacing_9$day]
equal_spacing_11$score <- logistic_data$score[logistic_data$day %in% equal_spacing_11$day]

#spacing schedules
equal_spacing_5 <- data.frame('day' = compute_measurement_schedule(time_period = 360, num_measurements = 5, smallest_int_length = 30, measurement_spacing = 'equal')$measurement_days)
time_inc_5 <- data.frame('day' = compute_measurement_schedule(time_period = 360, num_measurements = 5, smallest_int_length = 30, measurement_spacing = 'time_inc')$measurement_days)
time_dec_5 <- data.frame('day' = compute_measurement_schedule(time_period = 360, num_measurements = 5, smallest_int_length = 30, measurement_spacing = 'time_dec')$measurement_days)
mid_ext_5 <- data.frame('day' = compute_measurement_schedule(time_period = 360, num_measurements = 5, smallest_int_length = 30, measurement_spacing = 'mid_ext')$measurement_days)

time_inc_5$score <- logistic_data$score[logistic_data$day %in% time_inc_5$day]
time_dec_5$score <- logistic_data$score[logistic_data$day %in% time_dec_5$day]
mid_ext_5$score <- logistic_data$score[logistic_data$day %in% mid_ext_5$day]




mid_ext_5 <- ggplot(data = logistic_data, mapping = aes(x = day, y = score)) + 
  geom_line(linewidth = 1) + 
  geom_point(data = mid_ext_5, size = 5) + 
  scale_x_continuous(name = 'Day', breaks = seq(from = 0, to = 360, by = 60)) + 
  scale_y_continuous(name = 'Score', breaks = NULL) + 
  theme_classic(base_family = 'Helvetica') + 
  theme(axis.text = element_text(color = 'black', size = 16), 
        axis.title = element_text(size = 20))

ggsave(filename = 'Figures/mid_ext_5.png', plot = mid_ext_5, width = 8, height = 6)



```

@navarro2015

@yang2021

@mayer1995

@christian2011

@chen2011

```{r exercise-plots}

alpha <- 20 
theta <- 80
beta <- 40
gamma <- 10
delta <- 10
exercise_intensity <- 1:100

f(x) = theta + (alpha - theta) / (1 + exp((x - c) / d)) - (b - e) / (1 + exp((x - f) / g))

exp_dec <- eval(expr = theta + (alpha - theta)/(1 + exp((beta - exercise_intensity) * gamma)) ^ (-delta))

neg_exp <- data.frame(ha_risk = exp_dec, 
                      exercise_intensity = exercise_intensity)

ggplot(data = neg_exp, mapping = aes(x = exercise_intensity, y = ha_risk)) + 
  geom_line(linewidth = 1) + 
  theme_classic()

```






